version: "3"

services:
  app:
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.7
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/wechallenge:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
