version: "3"

services:
  app:
    user: vscode
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.7
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    links:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
